---
title: "Regional Supervisor Site Allocations - Iengineering"
author: "ATC"
date: "17 May 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r LoadLibraries, echo=FALSE, message=FALSE, warning=FALSE}
## Import Libraries
library(leaflet) ## Creating leaftlet map
library(xlsx) ## For reading excel file
library(dplyr) ## For data manipulation
```


# All Camusat Sites
   

```{r Iengineering, echo=FALSE, message=FALSE, warning=FALSE, fig.align="center"}
## Read the data
## Read the site data
sitedata <- read.xlsx("HOTO Teams 2020.xlsx", sheetName = "All sites list")

## Clean the data
## Select the rows for the Latitudes, Longitudes and Region
siteLocations <- sitedata[,c("Site.Name", "ATC.SID", 
                             "Latitude", "Longitude", "Proposed.O.M.Contractor", "HOTO.Plan")]
siteLocations <- siteLocations[siteLocations$HOTO.Plan != c("Retained Site"), ]
## Remove missing values data
#siteLocations <- na.omit(siteLocations)
# Check if all missing values are removed
#table(is.na(siteLocations))
# Check the structure of the data frame
#str(siteLocations)
# Change Name variable from Factor to character type
siteLocations$Site.Name <- as.character(siteLocations$Site.Name)
siteLocations$proposed.SMPMS.3 <- as.factor(siteLocations$HOTO.Plan)

## Remove wrong value of Mutara_House
#siteLocations <- siteLocations[!(siteLocations$ATC.Site.Name == c("Mutara_House")),]

# Setting your own colors manually:
pal <- colorFactor(
  palette = c('green', 'blue', 'purple', 'red','brown', 'green', "yellow"), #, "orange", "black", "purple", "pink", "brown", "grey"),
  domain = siteLocations$HOTO.Plan
)

#pal <- colorFactor(
#  palette = 'Dark2',
#  domain = siteLocations$Allocation)

## Plot the map
## Plot map according to the regions of the sites
leaflet(siteLocations) %>% addTiles() %>% addMarkers(group = siteLocations$HOTO.Plan, lat = siteLocations$Latitude, lng = siteLocations$Longitude, popup = paste("SiteName:" = siteLocations$Site.Name, "</br>",
                                                                                                                              "SiteID:" = siteLocations$Site.ID  ), clusterOptions = markerClusterOptions())

```

# Circular Pins  

### *Click circle to view Site Name and Site ID*
#### *Note: Different colour per supervisor*  

```{r CircularPins, echo=FALSE, message=FALSE, warning=FALSE}
#leaflet(siteLocations) %>% addTiles() %>% addMarkers(lat = siteLocations$Latitude, lng = siteLocations$Longitude) %>% addPopups(siteLocations$Site.Name,siteLocations$Site.ID, options = popupOptions(closeButton = FALSE))
leaflet(siteLocations) %>%
  addTiles() %>%
  addCircles(lat = siteLocations$Latitude, lng = siteLocations$Longitude, weight = 1, 
              popup = paste("SiteName:" = siteLocations$Site.Name, "</br>",                                                      "SiteID:" = siteLocations$Site.ID  ), 
             color = ~pal(HOTO.Plan), radius = 20000) #%>% addPopups(siteLocations$Site.Name,siteLocations$Site.ID, options = popupOptions(closeButton = FALSE))
```

# Pins for sites  

### *Click circle to view details of Site Name, Site ID and Supervisor*  
#### *Note: Different colour per supervisor*  
```{r testing, fig.width=12, fig.height=8, echo=FALSE, message=FALSE, warning=FALSE}
# fig.width=12, fig.height=8
pal <- colorFactor(
  palette = c('green', 'blue', 'purple', 'red','brown', 'green', "yellow"),#, "orange", "black", "purple", "pink", "brown", "grey"),
  domain = siteLocations$HOTO.Plan
)
leaflet() %>%
# Basic markers
addTiles(group = "basic") %>%
addMarkers(data = siteLocations, group = "basic", popup = paste("SiteName:" = siteLocations$Site.Name, "</br>",                                                                                        "SiteID:" = siteLocations$Site.ID,
                        "</br>",                                                                                        "Supervisor:" = siteLocations$HOTO.Plan      
                                                                )) %>%
# When zoomed in, we'll show circles at the base of each marker whose
# radius and color reflect the magnitude
addProviderTiles(providers$Stamen.TonerLite, group = "detail") %>%
addCircleMarkers(data = siteLocations, group = "detail", fillOpacity = 0.5,
radius = 25, color = ~pal(HOTO.Plan), stroke = FALSE) %>%
# Set the detail group to only appear when zoomed in
groupOptions("detail", zoomLevels = 7:18)
```
