---
title: "SitesLocations"
author: "Allan Kavuma"
date: "23 September 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r LoadLibraries, echo=FALSE, message=FALSE, warning=FALSE}
## Import Libraries
library(leaflet) ## Creating leaftlet map
library(xlsx) ## For reading excel file
library(dplyr) ## For data manipulation
```


```{r LoadData, echo=FALSE, message=FALSE, warning=FALSE}
## Read the data
## Read the site data
sitedata <- read.xlsx("RegionalSupervisorsSiteAllocation.xlsx", sheetName = "site list")
```


```{r CleanData, echo=FALSE, message=FALSE, warning=FALSE}
## Clean the data
## Select the rows for the Latitudes, Longitudes and Region
siteLocations <- sitedata[,c("Site.name", "Site.ID", 
                             "Latitude", "Longitude")]
## Remove missing values data
#siteLocations <- na.omit(siteLocations)
# Check if all missing values are removed
#table(is.na(siteLocations))
# Check the structure of the data frame
#str(siteLocations)
# Change Name variable from Factor to character type
siteLocations$Site.name <- as.character(siteLocations$Site.name)
## Remove wrong value of Mutara_House
#siteLocations <- siteLocations[!(siteLocations$ATC.Site.Name == c("Mutara_House")),]
```


```{r PlotMap, echo = FALSE, message=FALSE, warning=FALSE}
## Plot the map
## Plot map according to the regions of the sites
leaflet(siteLocations) %>% addTiles() %>% addMarkers(lat = siteLocations$Latitude, lng = siteLocations$Longitude, popup = paste("SiteName:" = siteLocations$Site.name, "</br>",
                                                                                                                              "SiteID:" = siteLocations$Site.ID  ), clusterOptions = markerClusterOptions())

#leaflet(siteLocations) %>% addTiles() %>% addMarkers(lat = siteLocations$Latitude, lng = siteLocations$Longitude) %>% addPopups(siteLocations$Site.name,siteLocations$Site.ID, options = popupOptions(closeButton = FALSE))
```